// Common New Zealand motor / motorcycle insurers
export const NZ_INSURERS: string[] = [
  "AA Insurance",
  "AMI Insurance",
  "AMP General Insurance",
  "ANZ Insurance",
  "ASB Insurance",
  "Assurant NZ",
  "BNZ Insurance",
  "Cove Insurance",
  "FMG (Farmers Mutual Group)",
  "Initio Insurance",
  "Lumley Insurance (IAG)",
  "MAS (Medical Assurance Society)",
  "NAC (New Zealand Automobile Club)",
  "NZI Insurance",
  "Police Health Plan / Police Welfare",
  "Protecta Insurance",
  "Provident Insurance",
  "Quest Insurance",
  "Star Insure",
  "State Insurance",
  "Swann Insurance",
  "Tower Insurance",
  "Trade Me Insurance",
  "Vero Insurance",
  "Westpac Insurance",
  "Youi NZ",
];
