export type WorkPreset = {
  id: string;
  label: string;
  group: "Service" | "Engine" | "Brakes" | "Suspension" | "Drivetrain" | "Electrical" | "Tyres & Wheels";
  hours: number;
  items: string[];
};

export const WORK_PRESETS: WorkPreset[] = [
  {
    id: "standard-service",
    label: "Standard Service",
    group: "Service",
    hours: 1.5,
    items: [
      "Engine oil drained and replaced with correct grade",
      "Oil filter replaced and sealing ring lubricated",
      "Drain plug torqued to spec",
      "Air filter inspected / cleaned",
      "Chain cleaned, lubricated and tension adjusted",
      "Tyre pressures and tread depth checked",
      "Brake pads, discs and fluid level inspected",
      "Lights, horn and indicators checked",
      "All fluid levels topped up",
      "Fasteners and controls checked for security",
      "Road test completed",
    ],
  },
  {
    id: "full-service",
    label: "Full Service",
    group: "Service",
    hours: 3,
    items: [
      "Engine oil and filter replaced with correct grade",
      "Drain plug and filter torqued to spec",
      "Air filter replaced",
      "Spark plugs inspected / replaced and gapped to spec",
      "Brake fluid replaced front and rear with fresh DOT 4 and system bled",
      "Coolant drained and replaced with correct spec coolant, system bled of air",
      "Clutch fluid replaced and system bled (hydraulic clutch models)",
      "Cable clutch free play adjusted and lubricated (cable clutch models)",
      "Final drive oil replaced (shaft drive models) / chain and sprockets inspected, cleaned, lubricated and adjusted",
      "Brake pads, discs and calipers inspected and cleaned",
      "Wheel bearings and steering head bearings checked",
      "Suspension inspected for leaks and operation",
      "Tyres inspected, pressures set",
      "Battery condition and charging system tested",
      "All lights and electrics checked",
      "Torque check on critical fasteners",
      "Extended road test completed",
    ],
  },

  {
    id: "pre-wof",
    label: "Pre-WOF Check",
    group: "Service",
    hours: 0.5,
    items: [
      "Tyres, tread depth and pressures checked",
      "Brakes tested for effectiveness and wear",
      "Lights, indicators and horn checked",
      "Steering head and wheel bearings checked for play",
      "Chain condition and tension checked",
      "Frame, exhaust and mirrors inspected",
    ],
  },
  {
    id: "fork-seal",
    label: "Fork Seal Replacement",
    group: "Suspension",
    hours: 2.5,
    items: [
      "Front end supported, wheel, mudguard and calipers removed",
      "Fork legs removed from triple clamps",
      "Forks stripped and old oil drained",
      "Old seals, dust seals and bushes removed and inspected",
      "Stanchions cleaned and checked for pitting",
      "New fork seals, dust seals and clips fitted",
      "Refilled with correct oil volume and grade",
      "Forks refitted and aligned, all fasteners torqued to spec",
      "Road test — no leaks, damping normal",
    ],
  },
  {
    id: "rear-shock",
    label: "Rear Shock Service / Replacement",
    group: "Suspension",
    hours: 2,
    items: [
      "Rear of bike supported and shock removed",
      "Linkage and bearings cleaned, inspected and greased",
      "Shock serviced / replaced",
      "Refitted and all fasteners torqued to spec",
      "Sag and preload set, road tested",
    ],
  },
  {
    id: "caliper-overhaul",
    label: "Brake Caliper Overhaul",
    group: "Brakes",
    hours: 2,
    items: [
      "Caliper removed and stripped",
      "Pistons removed, cleaned and inspected",
      "Seal grooves cleaned, new seal kit fitted",
      "Pistons lubricated and refitted",
      "New pads fitted where required",
      "Caliper refitted and torqued to spec",
      "System bled with fresh brake fluid",
      "Brake operation tested on road",
    ],
  },
  {
    id: "brake-pads-fluid",
    label: "Brake Pads & Fluid Change",
    group: "Brakes",
    hours: 1,
    items: [
      "Old pads removed, caliper and pistons cleaned",
      "New pads fitted and pins greased",
      "Discs measured for thickness and run-out",
      "Old brake fluid flushed and system bled with new fluid",
      "Brake operation tested on road",
    ],
  },
  {
    id: "chain-sprockets",
    label: "Chain & Sprocket Replacement",
    group: "Drivetrain",
    hours: 1.5,
    items: [
      "Rear wheel removed, old chain and sprockets removed",
      "Front and rear sprocket carriers and cush drive inspected",
      "New front and rear sprockets fitted and torqued to spec",
      "New chain fitted and riveted / joined",
      "Chain tension and wheel alignment set",
      "Chain lubricated, road tested",
    ],
  },
  {
    id: "clutch",
    label: "Clutch Plates Replacement",
    group: "Drivetrain",
    hours: 2.5,
    items: [
      "Oil drained and clutch cover removed",
      "Clutch pack removed and measured",
      "New friction and steel plates fitted, springs checked",
      "Cover refitted with new gasket, bolts torqued to spec",
      "Fresh oil refilled, clutch free play adjusted",
      "Clutch operation road tested",
    ],
  },
  {
    id: "valve-clearance",
    label: "Valve Clearance Adjustment",
    group: "Engine",
    hours: 3,
    items: [
      "Bodywork, tank and valve cover removed",
      "Engine set to TDC on compression for each cylinder",
      "All intake and exhaust clearances measured and recorded",
      "Shims / adjusters changed to bring clearances within spec",
      "Clearances re-checked after adjustment",
      "Valve cover refitted with new gasket, torqued to spec",
      "Engine run and checked for leaks",
    ],
  },
  {
    id: "carb-clean",
    label: "Carburettor Clean & Balance",
    group: "Engine",
    hours: 3,
    items: [
      "Carburettors removed and stripped",
      "Jets, passages and float bowls ultrasonically cleaned",
      "Floats and needle valves checked and set",
      "New o-rings / gaskets fitted where required",
      "Carbs refitted, throttle free play set",
      "Vacuum balanced and mixture set, road tested",
    ],
  },
  {
    id: "coolant-flush",
    label: "Coolant Flush",
    group: "Engine",
    hours: 1,
    items: [
      "Old coolant drained and system flushed",
      "Hoses and clamps inspected",
      "Refilled with correct coolant and bled of air",
      "Run up to temperature, fan operation checked, level topped",
    ],
  },
  {
    id: "brake-fluid",
    label: "Brake Fluid Replacement",
    group: "Brakes",
    hours: 0.75,
    items: [
      "Old brake fluid drained from front and rear systems",
      "Master cylinder reservoirs cleaned and inspected",
      "System refilled with fresh DOT 4 fluid and bled until clear",
      "Lines, hoses and seals checked for leaks",
      "Lever/pedal feel checked and brakes road tested",
    ],
  },
  {
    id: "clutch-fluid",
    label: "Clutch Fluid Replacement (Hydraulic)",
    group: "Drivetrain",
    hours: 0.5,
    items: [
      "Old clutch fluid drained from the hydraulic system",
      "Reservoir cleaned and inspected",
      "Refilled with fresh DOT 4 fluid and bled until clear",
      "Slave cylinder and line checked for leaks",
      "Clutch engagement checked and road tested",
    ],
  },
  {
    id: "final-drive-oil",
    label: "Final Drive / Gearbox Oil Change",
    group: "Drivetrain",
    hours: 0.5,
    items: [
      "Final drive oil drained and drain plug inspected",
      "Crush washers replaced",
      "Refilled with correct grade and quantity of final drive oil",
      "Plugs torqued to spec, checked for leaks and road tested",
    ],
  },

  {
    id: "battery-charging",
    label: "Battery & Charging System",
    group: "Electrical",
    hours: 0.75,
    items: [
      "Battery load tested and terminals cleaned",
      "Charging voltage tested at idle and at RPM",
      "Stator and regulator/rectifier output tested",
      "Battery replaced / recharged as required",
    ],
  },
  {
    id: "diagnostic-scan",
    label: "Diagnostic Scan",
    group: "Electrical",
    hours: 1,
    items: [
      "Fault codes read and recorded",
      "Live data reviewed against expected values",
      "Wiring, connectors and sensors inspected",
      "Fault diagnosed and findings reported to customer",
      "Codes cleared and system re-tested",
    ],
  },
  {
    id: "tyre-fit",
    label: "Tyre Replacement",
    group: "Tyres & Wheels",
    hours: 1,
    items: [
      "Wheel(s) removed and old tyre(s) dismounted",
      "Rim and bead seat cleaned and inspected",
      "New tyre(s) fitted, inflated and balanced",
      "Wheel(s) refitted, axle torqued to spec",
      "Chain tension / alignment re-checked, road tested",
    ],
  },
];

export function presetDetail(p: WorkPreset) {
  return p.items.map((i) => `• ${i}`).join("\n");
}
