/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPostBikeRouteImport } from './routes/_authenticated/post-bike'
import { Route as AuthenticatedMyWorkRouteImport } from './routes/_authenticated/my-work'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInsuranceRouteImport } from './routes/_authenticated/insurance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedClockRouteImport } from './routes/_authenticated/clock'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedMotorcyclesIndexRouteImport } from './routes/_authenticated/motorcycles.index'
import { Route as AuthenticatedLoanBikesIndexRouteImport } from './routes/_authenticated/loan-bikes.index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedInsuranceIndexRouteImport } from './routes/_authenticated/insurance.index'
import { Route as AuthenticatedGarageLibraryIndexRouteImport } from './routes/_authenticated/garage-library.index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings.index'
import { Route as AuthenticatedSettingsThemesRouteImport } from './routes/_authenticated/settings_.themes'
import { Route as AuthenticatedSettingsCapacityRouteImport } from './routes/_authenticated/settings_.capacity'
import { Route as AuthenticatedSettingsBookingTypesRouteImport } from './routes/_authenticated/settings_.booking-types'
import { Route as AuthenticatedMotorcyclesBikeIdRouteImport } from './routes/_authenticated/motorcycles.$bikeId'
import { Route as AuthenticatedLoanBikesBikeIdRouteImport } from './routes/_authenticated/loan-bikes.$bikeId'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated/jobs.new'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs.$jobId'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices.$invoiceId'
import { Route as AuthenticatedInsuranceNewRouteImport } from './routes/_authenticated/insurance.new'
import { Route as AuthenticatedInsuranceClaimIdRouteImport } from './routes/_authenticated/insurance.$claimId'
import { Route as AuthenticatedGarageLibraryModelIdRouteImport } from './routes/_authenticated/garage-library.$modelId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedBookingsNewRouteImport } from './routes/_authenticated/bookings.new'
import { Route as AuthenticatedBookingsBookingIdRouteImport } from './routes/_authenticated/bookings.$bookingId'
import { Route as AuthenticatedBookInsDateRouteImport } from './routes/_authenticated/book-ins.$date'
import { Route as AuthenticatedJobsJobIdInvoiceDraftRouteImport } from './routes/_authenticated/jobs_.$jobId.invoice-draft'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostBikeRoute = AuthenticatedPostBikeRouteImport.update({
  id: '/post-bike',
  path: '/post-bike',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyWorkRoute = AuthenticatedMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsuranceRoute = AuthenticatedInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClockRoute = AuthenticatedClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotorcyclesIndexRoute =
  AuthenticatedMotorcyclesIndexRouteImport.update({
    id: '/motorcycles/',
    path: '/motorcycles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoanBikesIndexRoute =
  AuthenticatedLoanBikesIndexRouteImport.update({
    id: '/loan-bikes/',
    path: '/loan-bikes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInsuranceIndexRoute =
  AuthenticatedInsuranceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInsuranceRoute,
  } as any)
const AuthenticatedGarageLibraryIndexRoute =
  AuthenticatedGarageLibraryIndexRouteImport.update({
    id: '/garage-library/',
    path: '/garage-library/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsThemesRoute =
  AuthenticatedSettingsThemesRouteImport.update({
    id: '/settings_/themes',
    path: '/settings/themes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCapacityRoute =
  AuthenticatedSettingsCapacityRouteImport.update({
    id: '/settings_/capacity',
    path: '/settings/capacity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsBookingTypesRoute =
  AuthenticatedSettingsBookingTypesRouteImport.update({
    id: '/settings_/booking-types',
    path: '/settings/booking-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMotorcyclesBikeIdRoute =
  AuthenticatedMotorcyclesBikeIdRouteImport.update({
    id: '/motorcycles/$bikeId',
    path: '/motorcycles/$bikeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoanBikesBikeIdRoute =
  AuthenticatedLoanBikesBikeIdRouteImport.update({
    id: '/loan-bikes/$bikeId',
    path: '/loan-bikes/$bikeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInsuranceNewRoute =
  AuthenticatedInsuranceNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInsuranceRoute,
  } as any)
const AuthenticatedInsuranceClaimIdRoute =
  AuthenticatedInsuranceClaimIdRouteImport.update({
    id: '/$claimId',
    path: '/$claimId',
    getParentRoute: () => AuthenticatedInsuranceRoute,
  } as any)
const AuthenticatedGarageLibraryModelIdRoute =
  AuthenticatedGarageLibraryModelIdRouteImport.update({
    id: '/garage-library/$modelId',
    path: '/garage-library/$modelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedBookingsNewRoute =
  AuthenticatedBookingsNewRouteImport.update({
    id: '/bookings/new',
    path: '/bookings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsBookingIdRoute =
  AuthenticatedBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookInsDateRoute =
  AuthenticatedBookInsDateRouteImport.update({
    id: '/book-ins/$date',
    path: '/book-ins/$date',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsJobIdInvoiceDraftRoute =
  AuthenticatedJobsJobIdInvoiceDraftRouteImport.update({
    id: '/jobs_/$jobId/invoice-draft',
    path: '/jobs/$jobId/invoice-draft',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clock': typeof AuthenticatedClockRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insurance': typeof AuthenticatedInsuranceRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/my-work': typeof AuthenticatedMyWorkRoute
  '/post-bike': typeof AuthenticatedPostBikeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/book-ins/$date': typeof AuthenticatedBookInsDateRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/garage-library/$modelId': typeof AuthenticatedGarageLibraryModelIdRoute
  '/insurance/$claimId': typeof AuthenticatedInsuranceClaimIdRoute
  '/insurance/new': typeof AuthenticatedInsuranceNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/loan-bikes/$bikeId': typeof AuthenticatedLoanBikesBikeIdRoute
  '/motorcycles/$bikeId': typeof AuthenticatedMotorcyclesBikeIdRoute
  '/settings/booking-types': typeof AuthenticatedSettingsBookingTypesRoute
  '/settings/capacity': typeof AuthenticatedSettingsCapacityRoute
  '/settings/themes': typeof AuthenticatedSettingsThemesRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/garage-library/': typeof AuthenticatedGarageLibraryIndexRoute
  '/insurance/': typeof AuthenticatedInsuranceIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/loan-bikes/': typeof AuthenticatedLoanBikesIndexRoute
  '/motorcycles/': typeof AuthenticatedMotorcyclesIndexRoute
  '/jobs/$jobId/invoice-draft': typeof AuthenticatedJobsJobIdInvoiceDraftRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clock': typeof AuthenticatedClockRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/my-work': typeof AuthenticatedMyWorkRoute
  '/post-bike': typeof AuthenticatedPostBikeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/book-ins/$date': typeof AuthenticatedBookInsDateRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/garage-library/$modelId': typeof AuthenticatedGarageLibraryModelIdRoute
  '/insurance/$claimId': typeof AuthenticatedInsuranceClaimIdRoute
  '/insurance/new': typeof AuthenticatedInsuranceNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/loan-bikes/$bikeId': typeof AuthenticatedLoanBikesBikeIdRoute
  '/motorcycles/$bikeId': typeof AuthenticatedMotorcyclesBikeIdRoute
  '/settings/booking-types': typeof AuthenticatedSettingsBookingTypesRoute
  '/settings/capacity': typeof AuthenticatedSettingsCapacityRoute
  '/settings/themes': typeof AuthenticatedSettingsThemesRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/garage-library': typeof AuthenticatedGarageLibraryIndexRoute
  '/insurance': typeof AuthenticatedInsuranceIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/loan-bikes': typeof AuthenticatedLoanBikesIndexRoute
  '/motorcycles': typeof AuthenticatedMotorcyclesIndexRoute
  '/jobs/$jobId/invoice-draft': typeof AuthenticatedJobsJobIdInvoiceDraftRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/clock': typeof AuthenticatedClockRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/insurance': typeof AuthenticatedInsuranceRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/my-work': typeof AuthenticatedMyWorkRoute
  '/_authenticated/post-bike': typeof AuthenticatedPostBikeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/book-ins/$date': typeof AuthenticatedBookInsDateRoute
  '/_authenticated/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/_authenticated/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/garage-library/$modelId': typeof AuthenticatedGarageLibraryModelIdRoute
  '/_authenticated/insurance/$claimId': typeof AuthenticatedInsuranceClaimIdRoute
  '/_authenticated/insurance/new': typeof AuthenticatedInsuranceNewRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/loan-bikes/$bikeId': typeof AuthenticatedLoanBikesBikeIdRoute
  '/_authenticated/motorcycles/$bikeId': typeof AuthenticatedMotorcyclesBikeIdRoute
  '/_authenticated/settings_/booking-types': typeof AuthenticatedSettingsBookingTypesRoute
  '/_authenticated/settings_/capacity': typeof AuthenticatedSettingsCapacityRoute
  '/_authenticated/settings_/themes': typeof AuthenticatedSettingsThemesRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/garage-library/': typeof AuthenticatedGarageLibraryIndexRoute
  '/_authenticated/insurance/': typeof AuthenticatedInsuranceIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/loan-bikes/': typeof AuthenticatedLoanBikesIndexRoute
  '/_authenticated/motorcycles/': typeof AuthenticatedMotorcyclesIndexRoute
  '/_authenticated/jobs_/$jobId/invoice-draft': typeof AuthenticatedJobsJobIdInvoiceDraftRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/analytics'
    | '/calendar'
    | '/clock'
    | '/customers'
    | '/dashboard'
    | '/insurance'
    | '/inventory'
    | '/invoices'
    | '/my-work'
    | '/post-bike'
    | '/settings'
    | '/templates'
    | '/users'
    | '/book-ins/$date'
    | '/bookings/$bookingId'
    | '/bookings/new'
    | '/customers/$customerId'
    | '/garage-library/$modelId'
    | '/insurance/$claimId'
    | '/insurance/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/loan-bikes/$bikeId'
    | '/motorcycles/$bikeId'
    | '/settings/booking-types'
    | '/settings/capacity'
    | '/settings/themes'
    | '/bookings/'
    | '/customers/'
    | '/garage-library/'
    | '/insurance/'
    | '/invoices/'
    | '/jobs/'
    | '/loan-bikes/'
    | '/motorcycles/'
    | '/jobs/$jobId/invoice-draft'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/analytics'
    | '/calendar'
    | '/clock'
    | '/dashboard'
    | '/inventory'
    | '/my-work'
    | '/post-bike'
    | '/settings'
    | '/templates'
    | '/users'
    | '/book-ins/$date'
    | '/bookings/$bookingId'
    | '/bookings/new'
    | '/customers/$customerId'
    | '/garage-library/$modelId'
    | '/insurance/$claimId'
    | '/insurance/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/loan-bikes/$bikeId'
    | '/motorcycles/$bikeId'
    | '/settings/booking-types'
    | '/settings/capacity'
    | '/settings/themes'
    | '/bookings'
    | '/customers'
    | '/garage-library'
    | '/insurance'
    | '/invoices'
    | '/jobs'
    | '/loan-bikes'
    | '/motorcycles'
    | '/jobs/$jobId/invoice-draft'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/account'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/clock'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/insurance'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/my-work'
    | '/_authenticated/post-bike'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/users'
    | '/_authenticated/book-ins/$date'
    | '/_authenticated/bookings/$bookingId'
    | '/_authenticated/bookings/new'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/garage-library/$modelId'
    | '/_authenticated/insurance/$claimId'
    | '/_authenticated/insurance/new'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/invoices/new'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/jobs/new'
    | '/_authenticated/loan-bikes/$bikeId'
    | '/_authenticated/motorcycles/$bikeId'
    | '/_authenticated/settings_/booking-types'
    | '/_authenticated/settings_/capacity'
    | '/_authenticated/settings_/themes'
    | '/_authenticated/bookings/'
    | '/_authenticated/customers/'
    | '/_authenticated/garage-library/'
    | '/_authenticated/insurance/'
    | '/_authenticated/invoices/'
    | '/_authenticated/jobs/'
    | '/_authenticated/loan-bikes/'
    | '/_authenticated/motorcycles/'
    | '/_authenticated/jobs_/$jobId/invoice-draft'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-bike': {
      id: '/_authenticated/post-bike'
      path: '/post-bike'
      fullPath: '/post-bike'
      preLoaderRoute: typeof AuthenticatedPostBikeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-work': {
      id: '/_authenticated/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof AuthenticatedMyWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance': {
      id: '/_authenticated/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AuthenticatedInsuranceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clock': {
      id: '/_authenticated/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof AuthenticatedClockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorcycles/': {
      id: '/_authenticated/motorcycles/'
      path: '/motorcycles'
      fullPath: '/motorcycles/'
      preLoaderRoute: typeof AuthenticatedMotorcyclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loan-bikes/': {
      id: '/_authenticated/loan-bikes/'
      path: '/loan-bikes'
      fullPath: '/loan-bikes/'
      preLoaderRoute: typeof AuthenticatedLoanBikesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/insurance/': {
      id: '/_authenticated/insurance/'
      path: '/'
      fullPath: '/insurance/'
      preLoaderRoute: typeof AuthenticatedInsuranceIndexRouteImport
      parentRoute: typeof AuthenticatedInsuranceRoute
    }
    '/_authenticated/garage-library/': {
      id: '/_authenticated/garage-library/'
      path: '/garage-library'
      fullPath: '/garage-library/'
      preLoaderRoute: typeof AuthenticatedGarageLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/themes': {
      id: '/_authenticated/settings_/themes'
      path: '/settings/themes'
      fullPath: '/settings/themes'
      preLoaderRoute: typeof AuthenticatedSettingsThemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/capacity': {
      id: '/_authenticated/settings_/capacity'
      path: '/settings/capacity'
      fullPath: '/settings/capacity'
      preLoaderRoute: typeof AuthenticatedSettingsCapacityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings_/booking-types': {
      id: '/_authenticated/settings_/booking-types'
      path: '/settings/booking-types'
      fullPath: '/settings/booking-types'
      preLoaderRoute: typeof AuthenticatedSettingsBookingTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motorcycles/$bikeId': {
      id: '/_authenticated/motorcycles/$bikeId'
      path: '/motorcycles/$bikeId'
      fullPath: '/motorcycles/$bikeId'
      preLoaderRoute: typeof AuthenticatedMotorcyclesBikeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loan-bikes/$bikeId': {
      id: '/_authenticated/loan-bikes/$bikeId'
      path: '/loan-bikes/$bikeId'
      fullPath: '/loan-bikes/$bikeId'
      preLoaderRoute: typeof AuthenticatedLoanBikesBikeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/insurance/new': {
      id: '/_authenticated/insurance/new'
      path: '/new'
      fullPath: '/insurance/new'
      preLoaderRoute: typeof AuthenticatedInsuranceNewRouteImport
      parentRoute: typeof AuthenticatedInsuranceRoute
    }
    '/_authenticated/insurance/$claimId': {
      id: '/_authenticated/insurance/$claimId'
      path: '/$claimId'
      fullPath: '/insurance/$claimId'
      preLoaderRoute: typeof AuthenticatedInsuranceClaimIdRouteImport
      parentRoute: typeof AuthenticatedInsuranceRoute
    }
    '/_authenticated/garage-library/$modelId': {
      id: '/_authenticated/garage-library/$modelId'
      path: '/garage-library/$modelId'
      fullPath: '/garage-library/$modelId'
      preLoaderRoute: typeof AuthenticatedGarageLibraryModelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/bookings/new': {
      id: '/_authenticated/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof AuthenticatedBookingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/$bookingId': {
      id: '/_authenticated/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof AuthenticatedBookingsBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book-ins/$date': {
      id: '/_authenticated/book-ins/$date'
      path: '/book-ins/$date'
      fullPath: '/book-ins/$date'
      preLoaderRoute: typeof AuthenticatedBookInsDateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs_/$jobId/invoice-draft': {
      id: '/_authenticated/jobs_/$jobId/invoice-draft'
      path: '/jobs/$jobId/invoice-draft'
      fullPath: '/jobs/$jobId/invoice-draft'
      preLoaderRoute: typeof AuthenticatedJobsJobIdInvoiceDraftRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
    AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedInsuranceRouteChildren {
  AuthenticatedInsuranceClaimIdRoute: typeof AuthenticatedInsuranceClaimIdRoute
  AuthenticatedInsuranceNewRoute: typeof AuthenticatedInsuranceNewRoute
  AuthenticatedInsuranceIndexRoute: typeof AuthenticatedInsuranceIndexRoute
}

const AuthenticatedInsuranceRouteChildren: AuthenticatedInsuranceRouteChildren =
  {
    AuthenticatedInsuranceClaimIdRoute: AuthenticatedInsuranceClaimIdRoute,
    AuthenticatedInsuranceNewRoute: AuthenticatedInsuranceNewRoute,
    AuthenticatedInsuranceIndexRoute: AuthenticatedInsuranceIndexRoute,
  }

const AuthenticatedInsuranceRouteWithChildren =
  AuthenticatedInsuranceRoute._addFileChildren(
    AuthenticatedInsuranceRouteChildren,
  )

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedClockRoute: typeof AuthenticatedClockRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInsuranceRoute: typeof AuthenticatedInsuranceRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedMyWorkRoute: typeof AuthenticatedMyWorkRoute
  AuthenticatedPostBikeRoute: typeof AuthenticatedPostBikeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedBookInsDateRoute: typeof AuthenticatedBookInsDateRoute
  AuthenticatedBookingsBookingIdRoute: typeof AuthenticatedBookingsBookingIdRoute
  AuthenticatedBookingsNewRoute: typeof AuthenticatedBookingsNewRoute
  AuthenticatedGarageLibraryModelIdRoute: typeof AuthenticatedGarageLibraryModelIdRoute
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
  AuthenticatedLoanBikesBikeIdRoute: typeof AuthenticatedLoanBikesBikeIdRoute
  AuthenticatedMotorcyclesBikeIdRoute: typeof AuthenticatedMotorcyclesBikeIdRoute
  AuthenticatedSettingsBookingTypesRoute: typeof AuthenticatedSettingsBookingTypesRoute
  AuthenticatedSettingsCapacityRoute: typeof AuthenticatedSettingsCapacityRoute
  AuthenticatedSettingsThemesRoute: typeof AuthenticatedSettingsThemesRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedGarageLibraryIndexRoute: typeof AuthenticatedGarageLibraryIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedLoanBikesIndexRoute: typeof AuthenticatedLoanBikesIndexRoute
  AuthenticatedMotorcyclesIndexRoute: typeof AuthenticatedMotorcyclesIndexRoute
  AuthenticatedJobsJobIdInvoiceDraftRoute: typeof AuthenticatedJobsJobIdInvoiceDraftRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedClockRoute: AuthenticatedClockRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInsuranceRoute: AuthenticatedInsuranceRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedMyWorkRoute: AuthenticatedMyWorkRoute,
  AuthenticatedPostBikeRoute: AuthenticatedPostBikeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedBookInsDateRoute: AuthenticatedBookInsDateRoute,
  AuthenticatedBookingsBookingIdRoute: AuthenticatedBookingsBookingIdRoute,
  AuthenticatedBookingsNewRoute: AuthenticatedBookingsNewRoute,
  AuthenticatedGarageLibraryModelIdRoute:
    AuthenticatedGarageLibraryModelIdRoute,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
  AuthenticatedLoanBikesBikeIdRoute: AuthenticatedLoanBikesBikeIdRoute,
  AuthenticatedMotorcyclesBikeIdRoute: AuthenticatedMotorcyclesBikeIdRoute,
  AuthenticatedSettingsBookingTypesRoute:
    AuthenticatedSettingsBookingTypesRoute,
  AuthenticatedSettingsCapacityRoute: AuthenticatedSettingsCapacityRoute,
  AuthenticatedSettingsThemesRoute: AuthenticatedSettingsThemesRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedGarageLibraryIndexRoute: AuthenticatedGarageLibraryIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedLoanBikesIndexRoute: AuthenticatedLoanBikesIndexRoute,
  AuthenticatedMotorcyclesIndexRoute: AuthenticatedMotorcyclesIndexRoute,
  AuthenticatedJobsJobIdInvoiceDraftRoute:
    AuthenticatedJobsJobIdInvoiceDraftRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
